#version 460

layout (local_size_x = 16, local_size_y = 16) in;

layout(rgba16f,set = 0, binding = 0) uniform image2D image;

struct ObjectData
{
    mat4;
    vec4 color;
};

layout(set = 0, binding = 2) buffer ObjectBuffer
{
    ObjectData objects[];
};

//push constants block
layout( push_constant ) uniform constants
{
 vec2 cameraPos;
 vec4 data3;
 vec4 data4;
 vec2 playerPos;
} PushConstants;

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

	ivec2 size = imageSize(image);

    vec4 topColor = PushConstants.data1;
    vec4 bottomColor = PushConstants.data2;

    if(length(PushConstants.playerPos - texelCoord) < 10){
        imageStore(image, texelCoord, vec4(1.0));
        return;
    }

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        float blend = float(texelCoord.y)/(size.y); 
    
        imageStore(image, texelCoord, mix(topColor,bottomColor, blend));
    }
}

